(package "super-project" "0.0.1" "...")

(source 'gnu)
(source 'melpa)

(development
 (depends-on "ecukes")
 (depends-on "espuds"))

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
