name: CI

on:
  pull_request:
    paths-ignore:
    - '**.md'
    - '**.markdown'
  push:
    paths-ignore:
    - '**.md'
    branches-ignore:
    - 'master'
    - 'main'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        emacs-version:
          - 26.3
          - 27.2
          - 28.2

    steps:
    - uses: actions/checkout@v3

    - uses: jcs090218/setup-emacs@master
      with:
        version: ${{ matrix.emacs-version }}

    - uses: actions/cache@v1
      with:
        path: ~/local
        key: ${{ runner.os }}-local-000

    - uses: actions/cache@v1
      with:
        path: ~/.emacs.d
        key: emacs.d

    - uses: jcs090218/setup-emacs@master
      with:
        version: ${{ matrix.emacs-version }}

    - uses: emacs-eask/setup-eask@master
      with:
        version: 'snapshot'

    - name: Run tests (Unix)
      if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
      continue-on-error: ${{ matrix.emacs_version == 'snapshot' }}
      run: |
        make test
      
    - name: Run tests (Windows)
      if: matrix.os == 'windows-latest'
      continue-on-error: ${{ matrix.emacs_version == 'snapshot' }}
      run: |
        make test-dos
      
